"""add product_class to products

Revision ID: 20870333551b
Revises: bd1883770bae
Create Date: 2025-09-30 23:43:15.399138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20870333551b'
down_revision = 'bd1883770bae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_class', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('product_class')

    # ### end Alembic commands ###
